name: Auto-assign Maintainer
"on":
  pull_request_target:
    types:
    - synchronize
    - reopened
    - labeled
    - unlabeled

jobs:
  core:
    name: Auto-assign Core Maintainer
    if:   ${{ github.event.pull_request.assignee == null && join(github.event.pull_request.assignees) == '' }}
    runs-on:
    - ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1.2.0
      with:
        configuration-path: .github/auto-assign-core.yml
  distribution:
    name: Auto-assign Distribution Maintainer
    if:   ${{ github.event.pull_request.assignee == null && join(github.event.pull_request.assignees) == '' }}
    runs-on:
    - ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1.2.0
      with:
        configuration-path: .github/auto-assign-distribution.yml
  implementation:
    name: Auto-assign Implementation Maintainer
    if:   ${{ github.event.pull_request.assignee == null && join(github.event.pull_request.assignees) == '' }}
    runs-on:
    - ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1.2.0
      with:
        configuration-path: .github/auto-assign-implementation.yml
  learning:
    name: Auto-assign Learning Maintainer
    if:   ${{ github.event.pull_request.assignee == null && join(github.event.pull_request.assignees) == '' }}
    runs-on:
    - ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1.2.0
      with:
        configuration-path: .github/auto-assign-learning.yml
  platform:
    name: Auto-assign Platform Maintainer
    if:   ${{ github.event.pull_request.assignee == null && join(github.event.pull_request.assignees) == '' }}
    runs-on:
    - ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1.2.0
      with:
        configuration-path: .github/auto-assign-platform.yml
